### ISSUE TITLE
How could I get my account back, if I've deleted my old email address, used for registration?

### ISSUE THREAD

**Issue by sgtpep** [django/djangopeople#53]
My old account page is https://people.djangoproject.com/sgtpep/. Its email address exists no more. Could you help me to get the access back to this account? Could you just delete it?

**Comment by garthk** [comment]
This still open as a means for others to get in touch about forgotten email addresses, @brutasse? I'd much appreciate having my [DP account](https://people.djangoproject.com/garthrk/) email reset to `firstname` `@` `githubID` `.` `com`, and the ID changed to match my github ID as I no longer have that surname. Can confirm via the registered Twitter, Facebook, and LinkedIn accounts.

**Comment by brutasse** [comment]
@garthk yes! I've just made the change. Let me know it it's ok now :)

**Comment by garthk** [comment]
Thanks, @brutasse; password reset worked fine.

**Comment by phu** [comment]
Sorry if there's a way to handle this that I missed, but I'm not seeing anything... the password reset didn't show up in any inbox I normally use, so I'm not sure where it would've gone. Are resets still being handled manually here?

**Comment by timgraham** [comment]
You can mail me your account details and I'll look into it.

**Comment by phu** [comment]
Thanks, Tim. My username is etremper.

On Jun 13, 2017 19:00, "Tim Graham" <notifications@github.com> wrote:

You can mail me your account details and I'll look into it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/django/djangopeople/issues/53#issuecomment-308068110>,
or mute the thread

**Comment by timgraham** [comment]
I sent you a mail to the hotmail address on file.
